[project]
name = "myapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ryosuke Mera", email = "liangyoumiliang@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.3",
]

[project.scripts]
myapp = "myapp:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
